[browser]
browser_path = "/root/ungoogled-chromium-139.0.7258.154-1-x86_64_linux/chrome"
browser_path_linux_test = "/root/ungoogled-chromium-139.0.7258.154-1-x86_64_linux/chrome"
browser_path_windows_test = "E:\\fingerprintbrowser\\ungoogled-chromium_139.0.7258.154-1.1_windows_x64\\chrome.exe"
